server:
  port: 8080

spring:
  application:
    name: core-baking
  flyway:
    baseline-on-migrate: true
    password: ${spring.r2dbc.password}
    user: ${spring.r2dbc.username}
    url: jdbc:postgresql://localhost:5432/core_banking
    locations: "filesystem:/core-banking-application/model/src/main/resources/db/migration"
    default-schema: accounting
  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/core_banking
    host: localhost
    port: 5432
    database: core_banking
    schema: accounting
    username: postgres
    password: postgres
#    pool:
#      max-size: 10
#      initial-size: 2
#      max-idle-time: 30s
#      max-life-time: 90s
#      max-create-connection-time: 30s

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
